question_data = [
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Science: Computers",
         "question": "Linux was first created as an alternative to Windows XP.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]
         },
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                          "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                           "question": "Linus Torvalds created Linux and Git.",
                                           "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                           "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
                                          "question": "DHCP stands for Dynamic Host Configuration Port.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                          "question": "Ada Lovelace is often considered the first computer programmer.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
         "correct_answer": "False", "incorrect_answers": ["True"]}]

